version: 1.0.{build}
image:
- Ubuntu

services:
- docker

environment:
  matrix:
    - ARCH: arm32v6
    - ARCH: arm64v8
    - ARCH: amd64

install:
  - sh: |
      sudo service docker start
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - sh: mkdir tmp
  - sh: |
      pushd tmp &&
      curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0-1/qemu-arm-static.tar.gz &&
      tar xzf qemu-arm-static.tar.gz &&
      popd
  - sh: |
      pushd tmp &&
      curl -L -o qemu-aarch64-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0-1/qemu-aarch64-static.tar.gz &&
      tar xzf qemu-aarch64-static.tar.gz &&
      popd

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1
